// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO9az2FlRnP0xuuvR763t3PJRdyRAE5dI',
    appId: '1:703889385243:web:3f48de4714b74f596c95be',
    messagingSenderId: '703889385243',
    projectId: 'aiteacher-61ce9',
    authDomain: 'aiteacher-61ce9.firebaseapp.com',
    storageBucket: 'aiteacher-61ce9.appspot.com',
    measurementId: 'G-BWVW257KBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqOWPCPnwPO_O7HxW4UxYwR8QdGdIjBwg',
    appId: '1:703889385243:android:aef810c33629b0256c95be',
    messagingSenderId: '703889385243',
    projectId: 'aiteacher-61ce9',
    storageBucket: 'aiteacher-61ce9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzuZVA78CwYs7O3Az0xcArjlLSRp1Q-8U',
    appId: '1:703889385243:ios:fa54fd02f698008b6c95be',
    messagingSenderId: '703889385243',
    projectId: 'aiteacher-61ce9',
    storageBucket: 'aiteacher-61ce9.appspot.com',
    iosClientId: '703889385243-7q51jvd6matscdgqll9pgnglqhleabns.apps.googleusercontent.com',
    iosBundleId: 'com.example.smathmathai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzuZVA78CwYs7O3Az0xcArjlLSRp1Q-8U',
    appId: '1:703889385243:ios:fa54fd02f698008b6c95be',
    messagingSenderId: '703889385243',
    projectId: 'aiteacher-61ce9',
    storageBucket: 'aiteacher-61ce9.appspot.com',
    iosClientId: '703889385243-7q51jvd6matscdgqll9pgnglqhleabns.apps.googleusercontent.com',
    iosBundleId: 'com.example.smathmathai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO9az2FlRnP0xuuvR763t3PJRdyRAE5dI',
    appId: '1:703889385243:web:bccb90a23cba07bb6c95be',
    messagingSenderId: '703889385243',
    projectId: 'aiteacher-61ce9',
    authDomain: 'aiteacher-61ce9.firebaseapp.com',
    storageBucket: 'aiteacher-61ce9.appspot.com',
    measurementId: 'G-M81NGTGL87',
  );
}
